language: clojure
  
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk10
    - jdk: openjdk11
    - os: osx
      jdk: openjdk11
      addons:
        homebrew:
          packages:
          - leiningen
          update: true

notifications:
  email:
    - "miro@titanoboa.io"
    
